### ISSUE TITLE
link_to with method causes error in console.

### ISSUE THREAD

**Issue by WriterZephos** [hotwired/turbo#521]
I think I am running into a bug when I converted some `link_to` links that stopped working with rails 7 to use the new `data-method` to work with turbo. The links have `data-method="delete"`.

Oddly, the link seems to work as intended but the console looks like a slasher movie with the following error:

````
Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#0:not([disabled])' is not a valid selector.
    at eval (eval at findFrameElement (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8199:28), <anonymous>:1:14)
    at FrameRedirector.findFrameElement (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8199:28)
    at FrameRedirector.shouldRedirect (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8193:26)
    at FrameRedirector.shouldSubmit (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8190:19)
    at FrameRedirector.shouldInterceptFormSubmission (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8176:19)
    at HTMLHtmlElement.FormInterceptor.submitBubbled (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:7141:51)
    at dispatch (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:6674:14)
    at Session.convertLinkWithMethodClickToFormSubmission (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8904:16)
    at Session.followedLinkToLocation (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8884:12)
    at LinkClickObserver.clickBubbled (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8299:29)
eval @ VM20911:1
findFrameElement @ turbo.es2017-esm.js:1894
shouldRedirect @ turbo.es2017-esm.js:1888
shouldSubmit @ turbo.es2017-esm.js:1885
shouldInterceptFormSubmission @ turbo.es2017-esm.js:1871
FormInterceptor.submitBubbled @ turbo.es2017-esm.js:789
dispatch @ turbo.es2017-esm.js:312
convertLinkWithMethodClickToFormSubmission @ turbo.es2017-esm.js:2627
followedLinkToLocation @ turbo.es2017-esm.js:2606
LinkClickObserver.clickBubbled @ turbo.es2017-esm.js:1996

````

Error is coming from this method:
````
    findFrameElement(element, submitter) {
        const id = (submitter === null || submitter === void 0 ? void 0 : submitter.getAttribute("data-turbo-frame")) || element.getAttribute("data-turbo-frame");
        if (id && id != "_top") {
            const frame = this.element.querySelector(`#${id}:not([disabled])`);
            if (frame instanceof FrameElement) {
                return frame;
            }
        }
    }
````

**Comment by WriterZephos** [comment]
Playing around with the `querySelector` function I realized it's the extra `#` and leading `0` in each of these errors that is the problem... but I have various things I am using for turbo_frame ids and the available delimiters are limited. Most special chars don't work with this function.

**Comment by WriterZephos** [comment]
Okay so there is indeed a way to escape special characters, and I think Turbo should do this automatically since it doesn't work otherwise. Seems like it should work with any characters that are allowed in any css id attribute.

Here is an example of non-escaped vs escaped id:

````
this.element.querySelector('#abcd#123:not([disabled])')
VM42750:1 Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#abcd#123:not([disabled])' is not a valid selector.
    at eval (eval at findFrameElement (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8199:28), <anonymous>:1:14)
    at FrameRedirector.findFrameElement (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8199:28)
    at FrameRedirector.shouldRedirect (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8193:26)
    at FrameRedirector.shouldSubmit (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8190:19)
    at FrameRedirector.shouldInterceptFormSubmission (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8176:19)
    at HTMLHtmlElement.FormInterceptor.submitBubbled (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:7141:51)
    at dispatch (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:6674:14)
    at Session.convertLinkWithMethodClickToFormSubmission (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8904:16)
    at Session.followedLinkToLocation (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8884:12)
    at LinkClickObserver.clickBubbled (http://localhost:3000/assets/application-d91808fa662411bc20da9c0dc0bbbc1b46daae0e30941d0b3d381d9112512388.js:8299:29)
eval @ VM42750:1
findFrameElement @ turbo.es2017-esm.js:1894
shouldRedirect @ turbo.es2017-esm.js:1888
shouldSubmit @ turbo.es2017-esm.js:1885
shouldInterceptFormSubmission @ turbo.es2017-esm.js:1871
FormInterceptor.submitBubbled @ turbo.es2017-esm.js:789
dispatch @ turbo.es2017-esm.js:312
convertLinkWithMethodClickToFormSubmission @ turbo.es2017-esm.js:2627
followedLinkToLocation @ turbo.es2017-esm.js:2606
LinkClickObserver.clickBubbled @ turbo.es2017-esm.js:1996
this.element.querySelector('#abcd\\#123:not([disabled])')
null
````

**Comment by acetinick** [comment]
Unless you trying to use UJS the syntax should be data-turbo-method=“delete”

**Comment by WriterZephos** [comment]
I think I was using it wrong. Closing.
