### ISSUE TITLE
v7.2.0-beta.2 doesn't accept turbo streams of `remove` action without a `template` child element

### ISSUE THREAD

**Issue by marcelolx** [hotwired/turbo#664]
In the latest beta release, we have seen the following error when we send a turbo-stream targeting an element to be removed from the DOM

```
Uncaught Error: <turbo-stream action="remove" target="target_element_here">: first child element must be a <template> element
    at HTMLElement.raise (turbo.es2017-esm.js:6517:1)
    at HTMLElement.get (turbo.es2017-esm.js:6497:1)
    at importStreamElements (turbo.es2017-esm.js:1036:1)
    at new StreamMessage (turbo.es2017-esm.js:1008:1)
    at Function.wrap (turbo.es2017-esm.js:1015:1)
    at StreamObserver.receiveMessageHTML (turbo.es2017-esm.js:4248:1)
    at StreamObserver.receiveMessageEvent (turbo.es2017-esm.js:4168:1)
    at TurboCableStreamSourceElement.dispatchMessageEvent (cable_stream_source_element.js:99:1)
    at subscriptions.js:128:1
    at Array.map (<anonymous>)
```

It seems that it is caused by the changes made in https://github.com/hotwired/turbo/pull/660 because now [here](https://github.com/hotwired/turbo/blob/main/src/core/streams/stream_message.ts#L25) we do access the `.templateElement` which does [raise an error](https://github.com/hotwired/turbo/blob/main/src/elements/stream_element.ts#L111-L116) if the child isn't a `template` element, but as we know the `remove` action doesn't require a child element https://turbo.hotwired.dev/reference/streams#remove

**Comment by dhh** [comment]
Solved by #665
